Import Libraries and load dataset

In [9]:
import pandas as pd
import numpy as np
dataset = pd.read_excel(r"C:\Users\renat\Documents\Data Science Projects\Classification\Book Purchases\Biblioteca2.xlsx")

In [10]:
dataset.head()

Titulo              Autor         Género   Precio  \
0        A monster\ncalls       Patrick Ness        Fantasy  2543.00   
1      Lord of the\nflies  William \nGolding        Fiction  1800.54   
2       How to stop\ntime         Matt Haigh        Fiction  2400.00   
3  Reasons to\nstay alive         Matt Haigh  Autobiography  1333.00   
4         Atomic \nHabits        James Clear      Self Help  2777.00   

   AñoPublicado  Paginas    Estado  
0          2011      224     Leido  
1          1954      272  Comprado  
2          2017      352  Comprado  
3          2015      272     Leido  
4          2018      320  Comprado

Feature Encoding

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
dataset['titulo'] = encoder.fit_transform(dataset.Titulo.values)
dataset['autor'] = encoder.fit_transform(dataset.Autor.values)
dataset['género'] = encoder.fit_transform(dataset.Género.values)
dataset['estado'] = encoder.fit_transform(dataset.Estado.values)

dataset['AñoPublicado'] = dataset['AñoPublicado'].astype(int) # Convertir año publicado a int
dataset['Paginas'] = dataset['Paginas'].astype(int)

In [22]:
print(dataset.dtypes)
print(dataset.columns)
print(dataset.head())

Titulo           object
Autor            object
Género           object
Precio          float64
AñoPublicado      int32
Paginas           int32
Estado           object
titulo            int32
autor             int32
género            int32
estado            int32
dtype: object
Index(['Titulo', 'Autor', 'Género', 'Precio', 'AñoPublicado', 'Paginas',
       'Estado', 'titulo', 'autor', 'género', 'estado'],
      dtype='object')
                   Titulo              Autor         Género   Precio  \
0        A monster\ncalls       Patrick Ness        Fantasy  2543.00   
1      Lord of the\nflies  William \nGolding        Fiction  1800.54   
2       How to stop\ntime         Matt Haigh        Fiction  2400.00   
3  Reasons to\nstay alive         Matt Haigh  Autobiography  1333.00   
4         Atomic \nHabits        James Clear      Self Help  2777.00   

   AñoPublicado  Paginas    Estado  titulo  autor  género  estado  
0          2011      224     Leido       0     22       4       1  
1

For the model to work better with some of the categorical values I had, I have encoded some of them and we can see that for 'Estado', 'Leido' corresponds to 1, 'Comprado' to 0, and 'No Comprado' to 2

In [13]:
X = dataset[['titulo', 'autor', 'género', 'Paginas', 'AñoPublicado', 'Precio']].to_numpy()
y = dataset['estado'].to_numpy()
print(X.shape)
print(y.shape)

(40, 6)
(40,)


In [14]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.40      0.67      0.50         3
           1       0.00      0.00      0.00         2
           2       0.67      0.67      0.67         3

    accuracy                           0.50         8
   macro avg       0.36      0.44      0.39         8
weighted avg       0.40      0.50      0.44         8

[[2 0 1]
 [2 0 0]
 [1 0 2]]


c:\Users\renat\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\renat\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\renat\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,